version: "3.8"

services:
  db:
    image: postgres:13
    container_name: xa-db-1
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:6
    container_name: xa-redis-1
    ports:
      - "6380:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  back:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: xa-back-1
    volumes:
      - .:/xa
    networks:
      - db
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      RUN_CELERY: "False"
    command: python manage.py runserver 0.0.0.0:8000

  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A config worker --loglevel=info
    container_name: xa-celery_worker-1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      RUN_CELERY: "True"

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile
    command: python -m celery -A config beat --loglevel=info
    container_name: xa-celery_beat-1
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      DJANGO_SETTINGS_MODULE: config.settings
      RUN_CELERY: "True"

volumes:
  postgres_data:

networks:
  db: